const BandActionTypes = {
    FETCH_BANDS_SUCCESS: 'FETCH_BANDS_SUCCESS',
    FETCH_BANDS_FAILURE: 'FETCH_BANDS_FAILURE',
    SELECT_BAND: 'SELECT_BAND',
    UPDATE_SELECTED_BAND: 'UPDATE_SELECTED_BAND'
}

export default BandActionTypes;